### ISSUE TITLE
Issues to solve for 1.3

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/Tomb-Editor#295]
Since 1.2 is released, I am moving some unfinished issues from 1.2 task list here:

- [x] Fix SEHException (#235).
- [x] Fix DEVICE_REMOVED (#290).
- [x] Fix RendererTextureAllocator crash on resource reloading (#301).
- [x] Fix texturing bugs (#291, #294, finally debug and fix vanilla wad upbloating from #278).
- [x] Test and re-test the MQO file import and export.
- [x] Add customizable backup.
- [x] Wad Tool: check static editor and custom meshes import.
- [x] Wad Tool: fix last broken things in skeleton editor.
- [x] Wad Tool: test it and make a specific videotutorial.
- [x] Wad Tool: restore loading of Prj2 files in animation editor.
- [x] Finish import of 3D models (MQO/OBJ/PLY/FBX/3DS, Metasequoia/Blender/3ds Max)
