### ISSUE TITLE
TIDE1 ToDo and issues

### ISSUE THREAD

**Issue by Nickelony** [MontyTRC89/Tomb-Editor#557]
- [ ] Add context menus back; (how did that even happen...)
- [ ] Check what's wrong with F1 taking too long to process stuff;
- [ ] Make #FIRST_ID actually functional;
- [ ] Try adding smart autocomplete for #INCLUDE file paths;
